name = "conquerday"
compatibility_date = "2024-02-17"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[redirects]]
source = "/*"
destination = "/index.html"
status = 200

[[redirects]]
source = "/admin/*"
destination = "/index.html"
status = 200
