[pages]
project_name = "conquerday"
routes = "/*"

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[site]
bucket = "./dist"

[env.production]
VITE_TEMPO = "false"
VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"