name = "conquerday"
type = "webpack"
compatibility_date = "2024-02-17"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
VITE_TEMPO = "false"

[build.upload]
format = "service-worker"