[pages]
project_name = "conquerday"
compatibility_date = "2024-02-17"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
pages_build_output_dir = "dist"

[[routes]]
pattern = "/*"
handler = "index"

[env.production]
VITE_TEMPO = "false"
VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"