name = "conquerday"
main = "./functions/notifications.ts"
compatibility_date = "2024-02-17"

[vars]
SUPABASE_URL = "https://yhcamkxphejjqlvnvebl.supabase.co"
TELEGRAM_BOT_TOKEN = "8118895697:AAG3XziOOuaN-fVyvCqrTZ169ms0BsSp64Q"

[triggers]
crons = ["* * * * *"] # Run every minute to handle notifications based on user timezones
